### ISSUE TITLE
Fix ThreadDialogHeading background.

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#115]
![image](https://github.com/bitcashorg/masterbots/assets/391270/c590603f-ac9f-4798-a7d6-9c6ecdb4ba78)

![Image](https://github.com/bitcashorg/masterbots/assets/391270/1d098e25-6019-4434-965b-6338ab2c28de)

You can modify the  AccordionTrigger and DialogTriggers from `@/components/ui/` if needed, make sure you dont break alignment on ThreadDialog, ThreadDoubleAccordion, ThreadAccordion

see https://dev.masterbots.ai

**Comment by Bran18** [comment]
### Update:

I am closing this issue by the following reasons: 

- The current UI differs from the one shown in the issue description.
