### ISSUE TITLE
Restore ThreadDoubleAccordion sticky effect

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#117]
guidelines

- if css only possible use css
- use standard methods and prop from radix and shadcn components. eg. onValueChange https://www.radix-ui.com/primitives/docs/components/select#controlling-the-value-displayed-in-the-trigger

**Comment by gaboesquivel** [comment]
I rwa eading the `router` docs, and it has scroll params, maybe that's all we need for the sticky accordion feature. `router.replace(href: string, { scroll: boolean })`.

**Comment by AndlerRL** [comment]
This might be already solved, but we have to check the alpha status if we need to do it there. On V0 we still have the sticky thread title. Assigning this to @TopETH , he originally worked on the sticky thread title.

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review and Fix Alpha/Search UI/UX Regressions](https://trello.com/c/9tuJtZmO/142-review-and-fix-alpha-search-ui-ux-regressions)
