### ISSUE TITLE
Discuss mobile nav ux options

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#133]
## Pills
https://github.com/bitcashorg/masterbots/assets/391270/f127fd94-23c2-4ccb-8963-5888e90b2c6d

## Selectors
![image](https://github.com/bitcashorg/masterbots/assets/391270/2bb92367-f569-4696-bf1d-a372528f5518)

## Full list and Drawer
![image](https://github.com/bitcashorg/masterbots/assets/391270/fcd85acc-4602-486d-9a55-2a86904cbd7e)
https://ui.shadcn.com/docs/components/drawer

**Comment by Bran18** [comment]
### Update:

I am closing this issue for the following reasons:

- Masterbots Search branch is no longer part of the current path. On the other hand, the current route path consists of two sidebars for mobile. One in the right for navigation and user profile-related actions, and the other in the left for the bot's selection and filtering.
