### ISSUE TITLE
Fix css details on ThreadDoubleAccordion

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#143]
![Image](https://github.com/bitcashorg/masterbots/assets/391270/a580d0e2-6d25-4957-9b71-133c1eb587cb)

see https://dev.masterbots.ai

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review and Fix Alpha/Search UI/UX Regressions](https://trello.com/c/9tuJtZmO/142-review-and-fix-alpha-search-ui-ux-regressions)
