### ISSUE TITLE
Fix unique insight aligment

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#144]
![Image](https://github.com/bitcashorg/masterbots/assets/391270/5c9baaec-c44a-4986-8752-23d314665e0e)

**Comment by TopETH** [comment]
@gaboesquivel How did you add a message to the database in branch 'alpha'?
I found that the message was formatted incorrectly compared to the 'main' branch. So did you add the messagse using a sql query or sth?
In the database of the `main` branch, messages have `\n\n` marks for line breaks. However, in the database of the `alpha` branch, they have `\n` marks for line breaks.

**Comment by Bran18** [comment]
### Update:

I am closing this issue for the following reasons:

- MB Search Branch is no longer in the route path.
- No response back since May 13. 

Note: The current route path has the `unique insight` well aligned and the clickable feature is handled under `lib/utils`
