### ISSUE TITLE
Metadata in search branch

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#159]
apply same metadata we hace in dev https://github.com/bitcashorg/masterbots/pull/158

**Comment by gaboesquivel** [comment]
Partially done, pending tasks:

- use dynamic og image on bot and user profile
- use correct metadata in category
- see if you can create a og image for category different than the default one on layout.
- make sure all public link have correct metadata

**Comment by Bran18** [comment]
@AndlerRL We should close this one.

Reason: Related to the Search branch

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brandon Development Support - October 2024](https://trello.com/c/SzgyUblj/239-brandon-development-support-october-2024)
