### ISSUE TITLE
Google analytics tag

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#161]
Setup google analytics tag G-N135BF99HS
https://nextjs.org/docs/messages/next-script-for-ga

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review and Fix Alpha UI/UX Regressions](https://trello.com/c/9tuJtZmO/142-review-and-fix-alpha-ui-ux-regressions)
