### ISSUE TITLE
Premium usernames and username generation

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#162]
Premium usernames under 10 chrar will require you to burn MBOT credits to get them.

For the alpha launch autogenerated usernames must follow the following format

- only alphanumeric and underscore 
- all lowercase
- min length 11
- max length 20 
- use oauth profile name to generate the name
- if oauth profile name is less than 10 chars ad `_{random_number}` suffix and with max length 11. eg `joe_0984533`
- if oauth name is larger than 20 chars truncate
- if oauth name is blank/undefined use this format `user_{random_number}` nd with max length 11. eg `user_431298`

 Tasks
- create library file called lib/username.ts
- export UsernameSchema ( zod schema )
- export function generateUsername(name:string)

Stack
- zod for validation
- typescript pure functions
- dont use external dependencies, write custom functions, they are simple

related to #160, after this that one is to make sure username is correctly used accross the codebase.

**Comment by gaboesquivel** [comment]
see https://github.com/bitcashorg/masterbots/blob/alpha/apps/masterbots.ai/lib/username.ts

**Comment by AndlerRL** [comment]
Right now we are using only the username as slug, but we are not adding more data on it, only if we found if the username slug generated has been already assigned, in that case will add a number, incrementing it depending how many casualties was found. It is similar as on Trello, where adds a number at the end. I thought about this by thinking on how friendly we can make the slugs for users and bots.

Do you think it is necessary to add the autogenerated numbers by default, @gaboesquivel ?

**Comment by Bran18** [comment]
### Update:

I am closing this issue for the following reasons:

- No response back since Apr 18 
- The MB Search Branch is no longer in the route path.
- The MB alpha branch is no longer in the route path.
