### ISSUE TITLE
Create url lib and fix url slugs

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#163]
Slug format

- all lowercase
- allowed separators `+`, `_`, `-`
- replace `&` with `_`
- replace ` & ` with `_` ( important: notice it is `<space>&<space>` different than previous)

Tasks

- create library file called lib/url.ts
- export SlugSchema ( zod schema )
- export `toSlug(separator:string)`
- export `fromSlug(separator:string)`

Stack

zod for validation
typescript pure functions
dont use external dependencies, write custom functions, they are simple

**Comment by gaboesquivel** [comment]
The lib are already created on alpha branch, make sure toSlug and fromSlug is used everywhere consistently

**Comment by TopETH** [comment]
@gaboesquivel 
I created the [PR](https://github.com/bitcashorg/masterbots/pull/173) for this issue.
Could you please review it?
