### ISSUE TITLE
Improve search results

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#166]
Search results are really bad.

Tasks
- improve query and use supabase server client and nextjs actions
- review conditions and params
- sort by date
- clean bad data on db 

Watch this video https://monosnap.com/file/cN9rU3fM1bfoQZlrxsJ2813DsiEyUM

**Comment by sheriffjimoh** [comment]
> @sheriffjimoh I am looking this is assigned to @TopETH , so it would be good to check status here.
> 
> Nathan - I think Jimoh can take this and you can take other tasks as well since you have been on another set of issue on another monorepo.

I will take this.

**Comment by Bran18** [comment]
@AndlerRL Another one related to search impro and other branch, we should close it

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brandon Development Support - October 2024](https://trello.com/c/SzgyUblj/239-brandon-development-support-october-2024)
