### ISSUE TITLE
Restore classname for active tab in categories tab

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#170]
Task
 - Pass the prop from server 
 - use client js to update on click

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review and Fix Alpha/Search UI/UX Regressions](https://trello.com/c/9tuJtZmO/142-review-and-fix-alpha-search-ui-ux-regressions)
