### ISSUE TITLE
Add dynamic category color to og image 

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#181]
related #140

this color is fixed to red
![image](https://github.com/bitcashorg/masterbots/assets/391270/109dfdbd-5ef5-4fa1-88bc-e830254e3001)

task
- create a color prop on chatbot schema and fill the database with correct values
- read the correct on `app/og/router`

**Comment by Bran18** [comment]
@AndlerRL we should close this one too. 

Reason: The team already worked on the OG image. 

Curren OG: 

![Screenshot 2024-10-03 at 3 40 08 PM](https://github.com/user-attachments/assets/28c3b169-2beb-438d-a41e-c4fa30ad2796)

**Comment by AndlerRL** [comment]
Thanks for checking this, Brandon. Closing as completed!

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brandon Development Support - October 2024](https://trello.com/c/SzgyUblj/239-brandon-development-support-october-2024)
