### ISSUE TITLE
Use consistent og image style/design across pages

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#182]

**Comment by sheriffjimoh** [comment]
@gaboesquivel  @AndlerRL  Any info on this?

**Comment by AndlerRL** [comment]
@sheriffjimoh -- I made this design for the OG image:

![image](https://github.com/bitcashorg/masterbots/assets/35474730/a247a60e-2339-4963-964b-e20b4cda15c6)

Figma: https://www.figma.com/file/nDZnCkmXwOo2I71TXDBQTs/Masterbots-AI?type=design&node-id=1009-5&mode=design&t=yc9MHZItOResvPQf-4

cc - @merivercap @gaboesquivel

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Dynamic OG Image](https://trello.com/c/IC71JYlv/153-create-dynamic-og-image)
