### ISSUE TITLE
Discuss simplify text on ThreadChat Inpu

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#189]
<img width="362" alt="image" src="https://github.com/bitcashorg/masterbots/assets/391270/c77a41cf-6891-4d6b-a494-20dca1809d35">

**Comment by AndlerRL** [comment]
What is that about? Isn't that the chat input on-site?

We already discussed the placeholder text with @merivercap. It is an old conversation about how we display the message to users. The original placeholder is the final version of Masterbots v0. We thought to keep it that way for a while, is there a concern to raise up in regards of the placeholder indication to users?

**Comment by Bran18** [comment]
@AndlerRL This one its for another branch that is not on the current track. On the other hand no response since Apr 23. 

We should close this one.

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brandon Development Support - October 2024](https://trello.com/c/SzgyUblj/239-brandon-development-support-october-2024)
