### ISSUE TITLE
Infinite Scroll and Search with Next Actions

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#198]
use supabase full text search https://supabase.com/docs/guides/database/full-text-search

**Comment by AndlerRL** [comment]
@sheriffjimoh — This is a great feature to implement on Masterbots, please check the docs related to this, but I cannot assign this due it seems it is assigned to Gabo.

@gaboesquivel — Is this a TODO or in progress? So I can assign Jimoh to this task.

**Comment by AndlerRL** [comment]
@sheriffjimoh — you might have a green light to do this one. Check the difference between V0 and the alpha version. On alpha I noticed an infinity scroll, but we have to confirm/double-check if we are using it with Nextjs actions.

**Comment by sheriffjimoh** [comment]
> @sheriffjimoh — you might have a green light to do this one. Check the difference between V0 and the alpha version. On alpha I noticed an infinity scroll, but we have to confirm/double-check if we are using it with Nextjs actions.

Is this not the update [here](https://github.com/bitcashorg/masterbots/compare/a503fd78cb8d...d55903f0b7b1)  🤔

**Comment by gaboesquivel** [comment]
on this PR https://github.com/bitcashorg/masterbots/pull/199

**Comment by sheriffjimoh** [comment]
> This is in progress on this PR #199

Okay thanks, is it different from this?  #166  ??

**Comment by AndlerRL** [comment]
@sheriffjimoh -- looks like issue #166 is co-related with this issue however, since they are related, seems also it will fit to do it on the same branch as PR #199 (or base a new branch from this one), so you can take the search results issue however, it is incomplete, so that might be a blocker for you. 

@gaboesquivel -- Is issue #166 a copy from this one? It has more specifications there but here looks that by implementing the full-text search will improve the search results hence, issue #166 gets redundant.

**Comment by Bran18** [comment]
@AndlerRL maybe it is a good idea to close this one and open a new one but for the current branch. 

### Reason: Currently our search only does "title" search

Video: 

https://github.com/user-attachments/assets/9330d1e3-2917-428a-90f6-34e0b824fe9e

**Comment by AndlerRL** [comment]
As [this comment](https://github.com/bitcashorg/masterbots/issues/183#issuecomment-2397761701), this will be closed. Thanks Brandon for the heads up!

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brandon Development Support - October 2024](https://trello.com/c/SzgyUblj/239-brandon-development-support-october-2024)
