### ISSUE TITLE
Breadcumb selector nav expeirment

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#200]
<img width="831" alt="image" src="https://github.com/bitcashorg/masterbots/assets/391270/fa7b9d4a-2325-48bd-afc9-cebfb1b7ef5f">

**Comment by AndlerRL** [comment]
Any more details about this? A dropdown showing the bots or something like that? Currently, the sidebar navigation does the same but in a unique way, where you can easily go back and select another bot.

**Comment by Bran18** [comment]
### Update:

I am closing this issue for the following reasons:

- No response back since Apr 23
- The MB Search Branch is no longer in the route path.
- The MB alpha branch is no longer in the route path.
