### ISSUE TITLE
Fix infinite scrolling

### ISSUE THREAD

**Issue by gaboesquivel** [bitcashorg/masterbots#220]
1. Currently there's a conflict with an accordion is expanded, for now simply remove threadId when loading a new page.

See problem https://monosnap.com/file/G0LCFB9ij7ppBpLXXzDNyT66gxe4kO

2. Use getThreads  response `meta` object value to stop calling more pages when there arent any more results.

3. Make sure loading is smooth and there's no unexpected scrolling behavior.

4. Add `loading items ... `  message while loading.

**Comment by Bran18** [comment]
@AndlerRL. This issue is no longer needed it. We should close it :raised_hands: 

Reason: We are now using hooks for scrolling and other strategies

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brandon Development Support - October 2024](https://trello.com/c/SzgyUblj/239-brandon-development-support-october-2024)
