### ISSUE TITLE
Thread list won´t redirect to profile pages [Regression]

### ISSUE THREAD

**Issue by AndlerRL** [bitcashorg/masterbots#243]
There must be an event obscuring happening on a recent change made on develop. Sharing video of the issue in comparison with production.

> **PRO TIP:** This might be due to a recent change done that was merged to development environment. Identifying the change would fix the issue by comparing both branches and seeing the differences on the `ThreadListItem` component.

## Failing to redirect to profile pages DEMO:

https://github.com/bitcashorg/masterbots/assets/35474730/e6f1d595-bbec-4d68-a9dd-218d5c013e7a

**Comment by Bran18** [comment]
@AndlerRL  @AnoukRImola 

Case Update: This one seems to be fixed, we should close this one

Preview: 

https://github.com/user-attachments/assets/51d1a6fe-a7d6-4a8d-af2b-0d3e27109881

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brandon Development Support - October 2024](https://trello.com/c/SzgyUblj/239-brandon-development-support-october-2024)
