### ISSUE TITLE
Improve WW API Data Sanitation.

### ISSUE THREAD

**Issue by AndlerRL** [bitcashorg/masterbots#277]
**Validate and Sanitize External API Responses Before Forwarding**

Directly forwarding the external API's response to the client without validation may pose security risks. The external API could return unexpected or malicious data. It's recommended to parse and validate the response content before sending it to the client to ensure that no harmful or sensitive data is transmitted.

Consider modifying the code to parse the response and safely send it to the client:

```diff
- return new NextResponse(response.body, {
-   headers: {
-     'Content-Type': 'text/event-stream',
-     'Cache-Control': 'no-cache',
-     'Connection': 'keep-alive',
-   },
- });
+ const data = await response.json();
+ return NextResponse.json(data, {
+   headers: {
+     'Cache-Control': 'no-cache',
+     'Connection': 'keep-alive',
+   },
+ });
```

> Committable suggestion was skipped due to low confidence.

_Originally posted by @coderabbitai[bot] in https://github.com/bitcashorg/masterbots/pull/276#discussion_r1784134942_

**Comment by Bran18** [comment]
I would like to take this one if no one else wants to take it :sunglasses:

**Comment by Bran18** [comment]
@AndlerRL  [PR284](https://github.com/bitcashorg/masterbots/pull/284) has an API sanitation.  Should we close this one?

**Comment by AndlerRL** [comment]
Yes of course! Thanks for handling this issue. :+1:
